### ISSUE TITLE
Window position in mac os x

### ISSUE THREAD

**Issue by dventura11** [alanboy/trello#19]
When you use the application in mac os x, the windows is blocked by the menu bar
![captura de pantalla 2015-05-27 a las 2 27 46](https://cloud.githubusercontent.com/assets/7266421/7831194/03d79e36-041a-11e5-8259-b507b1faf4ab.png)
.

**Comment by alanboy** [comment]
whats the fix? to move trello client elsewhere on a mac? like just below the menu bar?

**Comment by alanboy** [comment]
@dventura11 didn't this get fixed?

**Comment by dventura11** [comment]
yes, it did fixed already
