### ISSUE TITLE
No puedo construirlo.

### ISSUE THREAD

**Issue by lesthack** [alanboy/trello#5]
Alan,

Intente lo mismo que mane y obtuve lo mismo.

$ gradle build
…

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jhernandez/Downloads/debs & tar.gz/trello-0.1.0.0/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'trello-0.1.0.0'.
> Could not resolve all dependencies for configuration ':compile'.
   > Could not find org.trello4j:trello4j:1.0-SNAPSHOT.
     Required by:
         :trello-0.1.0.0:0.0.1-SNAPSHOT
…

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.913 secs

Que necesito para construirlo ?

**Comment by alanboy** [comment]
necesitas clonar y construir el submodulo que esta en la carpeta trello4j
